Feature/postgres for cluster (#58)
* increase size for apptainer's --writable-tmpfs

* add config settings to hopefully make postgres faster.

* some sql helpers

* forward postgres port from docker up to host

* More memory for --writable-tmpfs in apptainer

* allow for local postgres database

* Set statement_timeout using pre_execution query that works with local database

* Add code for github actions

* fix naming in apptainer instance start in docker_action.yml

* Simplify postgres instance naming in docker_action.yml

* fix rsync command

* Needed to add SUPABASE_LOCAL_URI

* Add test for database

* Update for Node 20

* Use URI for psql test

* instance run not instance start

* Update docker_action.yml

* Use temp directory instead of home directory for sandbox? maybe this will solve permission error?

* start local db with devcontainer

* add timeouts

* switch test to adamw because lamb requires cuda jit which fails on the ubuntu machine running github actions

* check if my_postgres_instance is running

* benchmark local and online dbs

* add rsync

* map db sandbox to scratch

* change default db to prod

---------

Co-authored-by: Daniel Milkie <dmilkie@gmail.com>

diff --git a/.github/workflows/docker_action.yml b/.github/workflows/docker_action.yml
--- a/.github/workflows/docker_action.yml
+++ b/.github/workflows/docker_action.yml
@@ -23,7 +23,7 @@ env:
   IMAGE_NAME: ${{ github.repository }} # github.repository as <account>/<repo>
   DO_SIGNING: ${{ false }}
   BRANCH: ${{ github.head_ref || github.ref_name }} # 'main' or 'develop'
-  PYTEST: python -m pytest --cache-clear -vvv --color=yes --disable-warnings -r fEX --junit-xml=test_results/test-results # will get appended with _data.xml, _utils.xml, _models.xml, _training.xml later...
+  PYTEST: python -m pytest --cache-clear -vvv --color=yes --disable-warnings -r fEX -s --log-cli-level=DEBUG -o log_cli=true --junit-xml=test_results/test-results # will get appended with _data.xml, _utils.xml, _models.xml, _training.xml later...
   TESTING: ${{ true }} # skip tests if we have this branch name
   # TESTMON_DATAFILE: ~/.cache/TESTMON/.testmondata  # where testmon stores its data file
 
@@ -79,7 +79,7 @@ jobs:
 
       # The repo gets volume mapped into the container automatically in test-docker
       - name: Checkout whole repo
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           submodules: "recursive"
 
@@ -119,7 +119,7 @@ jobs:
         uses: docker/setup-qemu-action@v3
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@v4
         with:
           driver: docker
 
@@ -127,7 +127,7 @@ jobs:
       # https://github.com/docker/login-action
       - name: Log into registry ${{ env.REGISTRY }}
         if: github.event_name != 'pull_request'
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ${{ env.REGISTRY }} # aka ghcr.io
           username: ${{ github.actor }}
@@ -137,7 +137,7 @@ jobs:
       # https://github.com/docker/metadata-action
       - name: Extract Docker metadata
         id: meta
-        uses: docker/metadata-action@v5
+        uses: docker/metadata-action@v6
         with:
           images: ${{ env.REGISTRY }}/${{ github.repository }}
           labels: |
@@ -151,7 +151,7 @@ jobs:
 
       - name: Build Docker image
         id: build-and-push
-        uses: docker/build-push-action@v6
+        uses: docker/build-push-action@v7
         with:
           context: .
           file: ./Dockerfile
@@ -204,7 +204,7 @@ jobs:
 
       # The repo gets volume mapped into the container automatically in test-docker
       - name: Checkout whole repo
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           submodules: "recursive"
 
@@ -218,7 +218,7 @@ jobs:
           ls -lhXR ${{ github.workspace }}
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@v4
         with:
           driver: docker
 
@@ -226,7 +226,7 @@ jobs:
       # https://github.com/docker/login-action
       - name: Log into registry ${{ env.REGISTRY }}
         if: github.event_name != 'pull_request'
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ${{ env.REGISTRY }} # aka ghcr.io
           username: ${{ github.actor }}
@@ -236,7 +236,7 @@ jobs:
       # https://github.com/docker/metadata-action
       - name: Extract Docker metadata
         id: meta
-        uses: docker/metadata-action@v5
+        uses: docker/metadata-action@v6
         with:
           images: ${{ env.REGISTRY }}/${{ github.repository }}
           labels: |
@@ -250,7 +250,7 @@ jobs:
 
       - name: Push Docker image
         id: docker-push
-        uses: docker/build-push-action@v6
+        uses: docker/build-push-action@v7
         with:
           context: .
           file: ./Dockerfile
@@ -300,6 +300,7 @@ jobs:
       SUPABASE_KEY: ${{ secrets.PRODUCTION_PROJECT_ANON_PUBLIC_KEY }}
       SUPABASE_PROD_URI: ${{ secrets.SUPABASE_PROD_URI }}
       SUPABASE_STAGING_URI: ${{ secrets.SUPABASE_STAGING_URI }}
+      SUPABASE_LOCAL_URI: ${{ secrets.SUPABASE_LOCAL_URI }}
     outputs:
       BUILT_SIF_PATH: ${{ steps.built_sif_path.outputs.BUILT_SIF_PATH }} # BUILT_SIF_FILE: /home/mosaic/Desktop/actions-runner/_work/cell_observatory_platform/cell_observatory_platform/feature_github_actions_updates_torch_26_01.sif
       SIF_FILE: ${{ steps.bootstrap_sif.outputs.SIF_FILE }}
@@ -311,7 +312,7 @@ jobs:
     steps:
       # The repo gets volume mapped into the container automatically
       - name: Checkout whole repo
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           submodules: "recursive"
 
@@ -323,7 +324,7 @@ jobs:
       # https://github.com/docker/login-action
       - name: Log into registry ${{ env.REGISTRY }}
         if: github.event_name != 'pull_request'
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ${{ env.REGISTRY }} # aka ghcr.io
           username: ${{ github.actor }}
@@ -529,6 +530,7 @@ jobs:
       SUPABASE_KEY: ${{ secrets.PRODUCTION_PROJECT_ANON_PUBLIC_KEY }}
       SUPABASE_STAGING_URI: ${{ secrets.SUPABASE_STAGING_URI }}
       SUPABASE_PROD_URI: ${{ secrets.SUPABASE_PROD_URI }}
+      SUPABASE_LOCAL_URI: ${{ secrets.SUPABASE_LOCAL_URI }}
       WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
       WANDB_USERNAME: ${{ secrets.WANDB_USERNAME }}
       WANDB_DATA_DIR: ${{ github.workspace }}
@@ -544,6 +546,27 @@ jobs:
       #   with:
       #     path: ${{ env.TESTMON_DATAFILE }}
       #     key: TESTMON_DATAFILE_${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-app-${{ hashFiles('**/apptainerfile.def') }}-dockerfile-${{ hashFiles('**/Dockerfile') }}-branchname
+
+      - name: Copy postgres database ~/db_files/sandbox to repo
+        run: |
+          rsync -av --delete ~/db_files/sandbox/ /tmp/sandbox/
+
+      - name: Start postgres database in apptainer in background
+        run: |
+          if apptainer instance list | grep -q "my_postgres_instance"; then
+            apptainer instance stop my_postgres_instance || true
+          fi
+
+          apptainer instance run --writable --env POSTGRES_PASSWORD=postgres /tmp/sandbox/ my_postgres_instance -c 'config_file=/etc/postgresql/postgresql.conf'
+
+          for i in {1..10}; do
+            if psql ${{ env.SUPABASE_LOCAL_URI }} --command="SELECT COUNT(*) FROM PREPARED;" && break; then
+              break
+            else
+              echo "Waiting for postgres to be ready..."
+              sleep 2
+            fi
+          done
 
       - name: List files in the repository
         run: |
@@ -612,6 +635,7 @@ jobs:
       - name: pytest /tests/ops
         if: ${{ env.TESTING }}
         run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} ${{ env.PYTEST }}_ops.xml tests/ops
+        timeout-minutes: 15
 
       - name: pytest /tests/data
         if: ${{ env.TESTING }}
@@ -620,24 +644,27 @@ jobs:
           timeout_minutes: 60
           max_attempts: 2
           command: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} ${{ env.PYTEST }}_data.xml tests/data
-    
+
       - name: pytest /tests/models
         if: ${{ env.TESTING }}
         run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} ${{ env.PYTEST }}_models.xml tests/models
+        timeout-minutes: 30
 
       - name: pytest /tests/training
         if: ${{ env.TESTING }}
         run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} ${{ env.PYTEST }}_training.xml tests/training
-      
+        timeout-minutes: 60
+
       - name: pytest /tests/evaluation
         if: ${{ env.TESTING }}
-        run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} ${{ env.PYTEST }}_ops.xml tests/evaluation
+        run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} ${{ env.PYTEST }}_evaluation.xml tests/evaluation
+        timeout-minutes: 15
 
       - name: print testmon2
         run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} ls -lhXRa ~/.cache/TESTMON
 
       - name: Publish Test Report
-        uses: mikepenz/action-junit-report@97744eca465b8df9e6e33271cb155003f85327f1 # "v5"
+        uses: mikepenz/action-junit-report@49b2ca06f62aa7ef83ae6769a2179271e160d8e4 # "v6.3.1"
         if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: "test_results/*.xml"
@@ -645,6 +672,11 @@ jobs:
           include_passed: true
           group_suite: false
           include_time_in_summary: true
+
+      - name: Stop postgres database in apptainer
+        if: always() # Ensure this runs even if previous steps fail
+        run: |
+          apptainer instance stop my_postgres_instance
 
   list_cache_folder:
     if: always() # always list the cache folder, even if the build failed.
