Feature/GitHub actions updates (#24)
* Update requirements.txt with new zarr version
* Fix Github actions

diff --git a/.github/workflows/docker_action.yml b/.github/workflows/docker_action.yml
--- a/.github/workflows/docker_action.yml
+++ b/.github/workflows/docker_action.yml
@@ -26,6 +26,7 @@ env:
   BRANCH: ${{ github.head_ref || github.ref_name }}   # 'main' or 'develop'
   PYTEST: python -m pytest --cache-clear -vvv --color=yes --disable-warnings -r fEX --junit-xml=test_results/test-results  # will get appended with _data.xml, _utils.xml, _models.xml, _training.xml later...
   TESTING: ${{ true }}  # skip tests if we have this branch name
+  TESTMON_DATAFILE: ~/.cache/TESTMON/.testmondata  # where testmon stores its data file
   
 jobs:
   cleanup-docker-runners:
@@ -243,7 +244,7 @@ jobs:
     permissions:
       contents: read
     outputs:
-      SIF_PATH: ${{ steps.step1.outputs.MY_PATH }}
+      SIF_PATH: ${{ steps.step1.outputs.MY_PATH }} # SIF_PATH: feature_github_actions_updates
     steps:
       - name: clean name of "/" characters
         id: step1
@@ -255,9 +256,9 @@ jobs:
               echo EOF
             } >> "$GITHUB_OUTPUT"            
             cat "$GITHUB_OUTPUT"
+            
 
-
-  apptainer-get-caches:
+  get-bootstrap-sif-and-paths:
     needs: sif_path
     runs-on:
       group: Default
@@ -268,16 +269,13 @@ jobs:
     env:
       SUPABASE_URL: ${{ secrets.PRODUCTION_PROJECT_URL }}
       SUPABASE_KEY: ${{ secrets.PRODUCTION_PROJECT_ANON_PUBLIC_KEY }}
-      TESTMON_DATAFILE: '/home/mosaic/TESTMON_DATAFILE'
     outputs:
-      BUILT_SIF_PATH: ${{ steps.built_sif_path.outputs.BUILT_SIF_PATH }}
-      SIF_FILE: ${{ steps.bootstrap_sif.outputs.SIF_FILE }}
+      BUILT_SIF_PATH: ${{ steps.built_sif_path.outputs.BUILT_SIF_PATH }}  # BUILT_SIF_FILE: /home/mosaic/Desktop/actions-runner/_work/platform/platform/feature_github_actions_updates_torch_cuda_12_8.sif
+      SIF_FILE: ${{ steps.bootstrap_sif.outputs.SIF_FILE }}   
       SIF_PYTORCH_VERSION: ${{ steps.sif_pytorch_version.outputs.SIF_PYTORCH_VERSION }}
       DOCKER_PYTORCH_VERSION: ${{ steps.dockerfile_pytorch_version.outputs.DOCKER_PYTORCH_VERSION }}
       DOCKER_PYTORCH_IMAGE: ${{ steps.dockerfile_pytorch_image.outputs.DOCKER_PYTORCH_IMAGE }}
-      CHECKSUM: ${{ steps.cached_apptainer_build.outputs.CHECKSUM }}
-
-      
+      # CHECKSUM: ${{ steps.cached_apptainer_build.outputs.CHECKSUM }}
 
     steps:
       # The repo gets volume mapped into the container automatically
@@ -338,7 +336,7 @@ jobs:
             echo "DOCKER_PYTORCH_IMAGE=$(grep -Po -m 1 'FROM \K.*(?= AS)' Dockerfile)" >> "$GITHUB_OUTPUT"
             cat "$GITHUB_OUTPUT"
 
-      - name: Copy bootstrap SIF file 
+      - name: Copy bootstrap SIF file ~/SIF_files/${{ steps.bootstrap_sif.outputs.SIF_FILE }} to repo
         continue-on-error: true # if it doesn't exist, keep going.
         run: |
             /bin/cp -sf ~/SIF_files/${{ steps.bootstrap_sif.outputs.SIF_FILE }} .
@@ -378,53 +376,56 @@ jobs:
             mkdir -p ~/SIF_files/  &&  apptainer build --nv --force ~/SIF_files/${{ steps.bootstrap_sif.outputs.SIF_FILE }} docker://${{ steps.dockerfile_pytorch_image.outputs.DOCKER_PYTORCH_IMAGE }}
 
   build_SIF_file_from_apptainerfile:
-    needs: apptainer-get-caches
+    needs: get-bootstrap-sif-and-paths
     runs-on:
       group: Default
     permissions:
-      contents: read
+      contents: write
       packages: write
       checks: write
     outputs:
       output1: ${{ steps.apptainer_build_definition_file.outcome }}
     steps:
-      - name: Cache apptainer build
-        uses: dmilkie/local-cache@main
+      - name: Cache folder ~/built_SIF
+        # uses: dmilkie/local-cache@main
+        uses: MasterworksIO/action-local-cache@2
         with:
-          base: ~/.cache/github_action_local_cache
+          # base: /home/mosaic/.cache/github_action_local_cache
+          strategy: copy
           path: /home/mosaic/built_SIF
           key: built_SIF_${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-app-${{ hashFiles('**/apptainerfile.def') }}-dockerfile-${{ hashFiles('**/Dockerfile') }}
 
-      - name: Check if built SIF file exists
+      - name: Copy cached apptainer to ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH}} if checksums pass
+        id: cached_apptainer_build
+        # remove old sif file in repo directory.  Then copy from cached version if it exists and checksum passes.
+        run: |
+            rm -f ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH}}  
+            sha256sum --check ~/built_SIF/checksum  &&  /bin/cp -fs ~/built_SIF/built.sif ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH}}  || true
+            sha256sum --check ~/built_SIF/checksum  &&  echo "CHECKSUM=SUCESS" > "$GITHUB_OUTPUT" || echo "CHECKSUM=FAILED" > "$GITHUB_OUTPUT"
+
+      - name: Check if built SIF file exists ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH}}
         id: check_if_built_SIF_exists
         uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6   # "version 3.0"
         env:
-          BUILT_SIF_FILE: ${{ needs.apptainer-get-caches.outputs.BUILT_SIF_PATH}}       
+          BUILT_SIF_FILE: ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH}}       
         with:
-          files: ${{ needs.apptainer-get-caches.outputs.BUILT_SIF_PATH}}
+          files: ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH}}
           ignore_case: true
           fail: false # fail on missing files
 
-      - name: Build "${{ needs.apptainer-get-caches.outputs.BUILT_SIF_PATH}}" from apptainerfile.def definition file
-        if: needs.apptainer-get-caches.outputs.CHECKSUM == 'FAILED' || steps.check_if_built_SIF_exists.outputs.files_exists == 'false'
+      - name: Build "${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH}}" from apptainerfile.def definition file
+        if: steps.cached_apptainer_build.outputs.CHECKSUM == 'FAILED' || steps.check_if_built_SIF_exists.outputs.files_exists == 'false'
         id: apptainer_build_definition_file
         continue-on-error: true
         run: |
-            /bin/cp -sf ~/SIF_files/${{ needs.apptainer-get-caches.outputs.SIF_FILE }} .
-            apptainer build --nv --force ${{ needs.apptainer-get-caches.outputs.BUILT_SIF_PATH }} apptainerfile.def
+            /bin/cp -sf ~/SIF_files/${{ needs.get-bootstrap-sif-and-paths.outputs.SIF_FILE }} .
+            apptainer build --nv --force ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH }} apptainerfile.def
                         
-            echo "done building ${{ needs.apptainer-get-caches.outputs.BUILT_SIF_PATH }}, now copying to ~/built_SIF for caching"
+            echo "done building ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH }}, now copying to ~/built_SIF for caching"
             mkdir -p ~/built_SIF
             sha256sum requirements.txt Dockerfile apptainerfile.def >  ~/built_SIF/checksum
-            /bin/cp -f ${{ needs.apptainer-get-caches.outputs.BUILT_SIF_PATH }} ~/built_SIF/built.sif
+            /bin/cp -f ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH }} ~/built_SIF/built.sif
 
-      - name: Copy cached apptainer build if checksums pass
-        id: cached_apptainer_build
-        run: |
-            rm -f ${{ steps.built_sif_path.outputs.BUILT_SIF_PATH }}
-            sha256sum --check ~/built_SIF/checksum  &&  /bin/cp -fs ~/built_SIF/built.sif ${{ steps.built_sif_path.outputs.BUILT_SIF_PATH }}  || true
-            sha256sum --check ~/built_SIF/checksum  &&  echo "CHECKSUM=SUCESS" > "$GITHUB_OUTPUT" || echo "CHECKSUM=FAILED" > "$GITHUB_OUTPUT"
-      
 
   build_SIF_file_from_dockerimage:
     if: needs.build_SIF_file_from_apptainerfile.outputs.output1 == 'failure' 
@@ -432,33 +433,35 @@ jobs:
     runs-on:
       group: Default
     permissions:
-      contents: read
+      contents: write
       packages: write
       checks: write
-    needs: [docker-build, docker-push, sif_path, apptainer-get-caches, build_SIF_file_from_apptainerfile]
+    needs: [docker-push, sif_path, build_SIF_file_from_apptainerfile, get-bootstrap-sif-and-paths]
     steps:
-      - name: Cache apptainer build
-        uses: dmilkie/local-cache@main
+      - name: Cache folder ~/built_SIF
+        # uses: dmilkie/local-cache@main
+        uses: MasterworksIO/action-local-cache@2
         with:
-          base: ~/.cache/github_action_local_cache
+          # base: /home/mosaic/.cache/github_action_local_cache
+          strategy: copy
           path: /home/mosaic/built_SIF
           key: built_SIF_${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-app-${{ hashFiles('**/apptainerfile.def') }}-dockerfile-${{ hashFiles('**/Dockerfile') }}
 
       - name: Build "${{ needs.sif_path.outputs.SIF_PATH }}_${{ env.CUDA_VERSION }}.sif" from docker://${{ needs.docker-push.outputs.IMAGENAME }}
         id: apptainer_build_docker_image
         run: |
-            apptainer build --nv --force ${{ needs.apptainer-get-caches.outputs.BUILT_SIF_PATH }} docker://${{ needs.docker-push.outputs.IMAGENAME }}
+            apptainer build --nv --force ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH }} docker://${{ needs.docker-push.outputs.IMAGENAME }}
                         
-            echo "done building ${{ needs.apptainer-get-caches.outputs.BUILT_SIF_PATH }}, now copying to ~/built_SIF for caching"
+            echo "done building ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH }}, now copying to ~/built_SIF for caching"
             mkdir -p ~/built_SIF
             sha256sum requirements.txt Dockerfile apptainerfile.def >  ~/built_SIF/checksum
-            /bin/cp -f ${{ needs.apptainer-get-caches.outputs.BUILT_SIF_PATH }} ~/built_SIF/built.sif
+            /bin/cp -f ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH }} ~/built_SIF/built.sif
 
-      - name: Copy cached apptainer build if checksums pass
+      - name: Copy apptainer build if checksums pass
         id: cached_apptainer_build
         run: |
-            rm -f ${{ steps.built_sif_path.outputs.BUILT_SIF_PATH }}
-            sha256sum --check ~/built_SIF/checksum  &&  /bin/cp -fs ~/built_SIF/built.sif ${{ steps.built_sif_path.outputs.BUILT_SIF_PATH }}  || true
+            rm -f ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH}}
+            sha256sum --check ~/built_SIF/checksum  &&  /bin/cp -fs ~/built_SIF/built.sif ${{ needs.get-bootstrap-sif-and-paths.outputs.BUILT_SIF_PATH}}  || true
             sha256sum --check ~/built_SIF/checksum  &&  echo "CHECKSUM=SUCESS" > "$GITHUB_OUTPUT" || echo "CHECKSUM=FAILED" > "$GITHUB_OUTPUT"
       # on error build from the apptainer.def file, we will build the SIF file from the docker image, if that doesn't work go to the (local) docker image.
 
@@ -469,6 +472,7 @@ jobs:
       #       apptainer push -U ${{ github.workspace }}/${{ needs.sif_path.outputs.SIF_PATH }}_${{ env.CUDA_VERSION }}.sif oras://ghcr.io/${{ github.repository }}:${{ github.head_ref || github.ref_name }}_${{ env.CUDA_VERSION }}_sif
 
 
+  # if you rename "apptainer-test" to "test", you must also rename this in the branch protection rules. https://github.com/cell-observatory/platform/settings/branch_protection_rules/60118126
   apptainer-test:
     needs: [build_SIF_file_from_dockerimage, build_SIF_file_from_apptainerfile, sif_path]
     if: |
@@ -478,27 +482,17 @@ jobs:
     runs-on:
       group: Default
     permissions:
-      contents: read
+      contents: write
       packages: write
       checks: write
     env:
       SUPABASE_URL: ${{ secrets.PRODUCTION_PROJECT_URL }}
       SUPABASE_KEY: ${{ secrets.PRODUCTION_PROJECT_ANON_PUBLIC_KEY }}
-      TESTMON_DATAFILE: '/home/mosaic/TESTMON_DATAFILE'
-    steps:
-
-      - name: Cache apptainer build
-        uses: dmilkie/local-cache@main
+    steps:      
+      - name: Cache pytest .testmondata
+        uses: actions/cache@v4
         with:
-          base: ~/.cache/github_action_local_cache
-          path: /home/mosaic/built_SIF
-          key: built_SIF_${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-app-${{ hashFiles('**/apptainerfile.def') }}-dockerfile-${{ hashFiles('**/Dockerfile') }}
-      
-      - name: Cache pytest testmon
-        uses: dmilkie/local-cache@main
-        with:
-          base: ~/.cache/github_action_local_cache
-          path: /home/mosaic/TESTMON_DATAFILE
+          path: ${{ env.TESTMON_DATAFILE }}
           key: TESTMON_DATAFILE_${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-app-${{ hashFiles('**/apptainerfile.def') }}-dockerfile-${{ hashFiles('**/Dockerfile') }}
           
       - name: List files in the repository
@@ -521,7 +515,13 @@ jobs:
         id: apptainer_run
         run: |
           rm -f test_results/* || true
-          echo "APPTAINER_RUN=apptainer exec --no-home --nv ${{ github.workspace }}/${{ needs.sif_path.outputs.SIF_PATH }}_${{ env.CUDA_VERSION }}.sif" >> "$GITHUB_OUTPUT"
+          echo "APPTAINER_RUN=apptainer exec --userns --no-home --bind ~/.cache/TESTMON --nv ${{ github.workspace }}/${{ needs.sif_path.outputs.SIF_PATH }}_${{ env.CUDA_VERSION }}.sif" >> "$GITHUB_OUTPUT"
+  
+      - name: print environment variables
+        run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} env
+
+      - name: print testmon 
+        run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} ls -lhXRa ~/.cache/TESTMON
 
       - name: pip list 
         run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} pip list
@@ -541,6 +541,10 @@ jobs:
         if: ${{ env.TESTING }}
         run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} ${{ env.PYTEST }}_models.xml --testmon   tests/models
 
+      - name: print testmon2 
+        run: ${{ steps.apptainer_run.outputs.APPTAINER_RUN }} ls -lhXRa ~/.cache/TESTMON
+      
+
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@97744eca465b8df9e6e33271cb155003f85327f1  # "v5"
         if: success() || failure() # always run even if the previous step fails
@@ -553,16 +557,29 @@ jobs:
 
   list_cache_folder:
     if: always() # always list the cache folder, even if the build failed.
+    permissions:
+      contents: read
+      packages: write
+      checks: write
     runs-on:
       group: Default
+    continue-on-error: true
     needs: [apptainer-test]
     steps:
-    - name: List cache folder
+    - name: List runner.tool_cache folder
+      continue-on-error: true
       run: |
-        ls -lhXR ~/.cache/github_action_local_cache
-    - name: List built_SIF folder
+        ls -alhXR ${{ runner.tool_cache }}
+      
+    - name: List ~/.cache/TESTMON folder
+      continue-on-error: true
       run: |
-        ls -lhXR /home/mosaic/built_SIF
+        ls -alhXR ~/.cache/TESTMON
+    - name: List /home/mosaic/built_SIF folder
+      continue-on-error: true
+      run: |
+        ls -alhXR /home/mosaic/built_SIF
+    
 
       # - name: Surface failing tests
       #   if: always()
